### ISSUE TITLE
other programming languages on upsilon

### ISSUE THREAD

**Issue by Oreig403** [UpsilonNumworks/Upsilon#159]
Would it be possible to modify the python app to interpret different programming languages (c, cpp, java, etc)

**Comment by AlexandreArduino** [comment]
you can't interpret c, c++ or rust languages because they are  compiled languages. Java can be added but it is too complicated and not really necessary. The purpose of the calculator was to add the python language for the exams. And the calculator has limited memory so if you add another language you will probably need to remove other apps :(

**Comment by Lauryy06** [comment]
Yes, for java for example, the virtual machine needs at least 4mb of RAM to run (see [here](https://stackoverflow.com/questions/235315/what-is-the-lightest-java-virtual-machine-ever-except-kvm)). So the capabilities of the calculator are too limited to add a more complicated language than Python...
This is an "impossible" problem to solve, so I'll close it.

**Comment by farvardin** [comment]
It should probably be possible to add lua which has a small footprint and which is cool... 😃
