### ISSUE TITLE
(reader app) issue when scrolling up a text after pressing the button home

### ISSUE THREAD

**Issue by mathurien** [UpsilonNumworks/Upsilon#176]
**Describe the bug**
when you go on the reader app and you scroll down a text, if you press the home button and you go back to your text in the reader, you won't be able to scroll up anymore

**To Reproduce**
1. go to the reader app
2. select a text
3. scroll down your text
4. press the home button
5. go back to the text in the reader app
6. try to scroll up
7. see issue

**Screenshots**

https://user-images.githubusercontent.com/101398581/158471737-bf86db82-2191-498c-b916-cff8d70e7fdd.mp4

**Device (please complete the following information):**
 - The device on which you're running Upsilon : n110
 - Upsilon Version: 1.0.0-dev
 - Upsilon commit: public

**Comment by fmOOmf** [comment]
Hello.

Same issue  for me :  randomly, the "reader"  app freezes, requiring a hard reset.
I think it appears when (but not every time) one quits reading whereas not being in the first page.
When coming back to reader, reader resumes displaying (it displays the same page than before quiting : there is a memory). Then randomly, it freezes when scrolling up.

If this behavior is confirmed, it means there is a way to avoid the freeze, going up to the first page before quiting the app.
It may help until the issue is fixed.

**Comment by fmOOmf** [comment]
Bonjour à toute l'équipe.
Avec la rev01 stable :
Impossible de revenir dans les pages précédentes d'un fichier liseuse qu'on a déjà commencé à lire. Ca dit : "Attention à la syntaxe". Il faut reset pour fix.
Peut-on désactiver la mémorisation du curseur ?

**Comment by Lauryy06** [comment]
Est-il possible d'avoir un exemple de fichier qui a ce bug ?

**Comment by fmOOmf** [comment]
Bonjour.
Oui, par exemple celui-ci.
Si on va en page 2, et qu'on quitte la lecture du fichier. 
Alors quand on ré-ouvre le fichier, il se positionne bien en page 2, mais il est impossible de remonter en page 1.
On ne peut pas uploader un *.urt => je le transmets par discord.

**Comment by Lauryy06** [comment]
It's fixed ! 2a234305f331b38199c7d61798e06a9ab050aa3d

**Comment by fmOOmf** [comment]
Merci Lauryy !
Cela va aider à démocratiser l'utilisation de Upsilon.

---

Great ! Thanks a lot.
