### ISSUE TITLE
Upsilon crash souvent

### ISSUE THREAD

**Issue by Frablock** [UpsilonNumworks/Upsilon#257]
Upsilon crash trop souvent

Aucune procédure requise, les crashs surviennent aléatoirement

Calculatrice : N110

**Comment by Yaya-Cout** [comment]
What's your Upsilon version ?

**Comment by Lauryy06** [comment]
Is it possible to have more information? How long have you been using it, what applications do you use, etc... ?

**Comment by Frablock** [comment]
Version 1.0.0 official
Cela survient avec python, je n'ai pas testé avec d'autres applications
Le système a été réinstallé avec le mode recovery plusieurs fois, et à chaque fois, quelques minutes plus tard, la calculatrice crash

**Comment by Cyber-Thibaut** [comment]
Can you give us a link to the script you have launched?

If you didn't run a script at least tell us what you did so we can see on our side to fix this bug

**Comment by hugo-b-r** [comment]
> Version 1.0.0 official Cela survient avec python, je n'ai pas testé avec d'autres applications Le système a été réinstallé avec le mode recovery plusieurs fois, et à chaque fois, quelques minutes plus tard, la calculatrice crash

C'est la version stable ?

**Comment by Yaya-Cout** [comment]
Dans la version 1.0.0, il y a un bug dans l'éditeur Python, après trois ouvertures d'un script, Upsilon crash, mais c'est corrigé dans la version de développement installable depuis le site.

---

In the 1.0.0 version, there is a bug in the Python app, after three opening of a script, Upsilon crash, but it's fixed in the development version, installable from the website.

**Comment by Frablock** [comment]
Ok, merci
