### ISSUE TITLE
Bootloader cannot start any firmware

### ISSUE THREAD

**Issue by Alerymin** [UpsilonNumworks/Upsilon#362]
**Describe the bug**
When I try to start any firmware, the bootloader freezes and the firmware does not start

**To Reproduce**
1. Install latest bootloader
2. Start the bootloader
3. Press 1, 2 or 3 to start a firmware
4. The calculator freezes

**Expected behavior**
Upsilon / Epsilon starts normally

**Screenshots**
![IMG_20240403_185007_652](https://github.com/UpsilonNumworks/Upsilon/assets/55508107/39bbdedb-f791-43b7-bf04-14b9ed000c83)

![IMG_20240403_185018_391](https://github.com/UpsilonNumworks/Upsilon/assets/55508107/57955c44-4f89-4cb8-a425-cf1860c52d5a)

**Device (please complete the following information):**
 - The device on which you're running Upsilon: n0110
 - Upsilon bootloader Version: 1.0.10
 - Upsilon commit: 5101436

**Comment by Yaya-Cout** [comment]
I don't know why it does that, but I know where it comes from : newer versions of the toolchain made the bootloader compilation crash. I don't know if the bug is in the toolchain or in Upsilon
A temporary fix I use is to downgrade the toolchain. On Arch Linux, you can do that manually or use the `downgrade` AUR package (with a graphical interface).
I didn't test every toolchain version (because it is long to download every version), but I know it is working on 11.3.0 (which I use).

**Comment by BloomyInDev** [comment]
Can this version be used in Github actions build ?

**Comment by Alerymin** [comment]
I preferred falling back to Omega's bootloader, this issue should be investigated further. I'm not qualified enough to do it though

**Comment by Yaya-Cout** [comment]
Fixed in 5e83c03f8d57ea463b1d73390800d25858ae30a6.
